apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodedb-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodedb-app
  template:
    metadata:
      labels:
        app: nodedb-app
    spec:
      containers:
      - name: nodedb-app
        image: bhargavbhalodiya04/node:01

      - name: mongodb
        image: mongo:latest